
CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(10) NOT NULL,
    ativo TINYINT(1) NOT NULL,
    papel VARCHAR(50),
    data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP
);
